KG.Pos.App/Controllers/WareHouseController.cs
using System;
using KG.Core.Services;
using KG.Infrastructure;
using KG.Core.Services.User;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using KG.Core.Services.WareHouse;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.DataProtection;
using System.Linq;
using KG.Core.Services.Configuration;
using KG.Core.Services.Procurement;
using Microsoft.Extensions.Configuration;
using System.Net;
using KG.Core.Services.Marketing;

namespace Erp.App.Controllers
{
    public class WareHouseController : Controller
    {
        private readonly ILogger _logger;
        private readonly WareHouseService _service;
        private readonly SessionHandler _sessionHandler;
        private readonly string connString;
        private readonly MarketingSaleService _marketingSaleService;

        public WareHouseController(InfrastructureDbContext db, ILogger<WareHouseController> logger, IHttpContextAccessor httpContextAccessor, IDataProtectionProvider idataProtectionProvide, IConfiguration configuration)
        {
            _logger = logger;
            _sessionHandler = new SessionHandler(db, httpContextAccessor.HttpContext);
            _sessionHandler.Adjust();
            _service = new WareHouseService(db, httpContextAccessor.HttpContext, idataProtectionProvide);
            connString = configuration.GetConnectionString("KgMsSqlConnection");
            _marketingSaleService = new MarketingSaleService(db, httpContextAccessor.HttpContext);

        }



        public async Task<IActionResult> GetCommonProductSubCategory(int id)


        {
            if (id < 0) { return RedirectToAction("Error", "Home"); }

            var model = await Task.Run(() => _service.CommonProductSubCategoryGet(id));
            var list = model.Select(x => new { Value = x.ID, Text = x.Name }).OrderBy(x => x.Text).ToList();
            return Json(list);
        }
        public async Task<IActionResult> GetCommonProduct(int id)
        {
            if (id < 0) { return RedirectToAction("Error", "Home"); }

            var model = await Task.Run(() => _service.CommonProductGet(id));
            var list = model.Select(x => new { Value = x.ID, Text = x.Name }).OrderBy(x => x.Text).ToList();

            _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + "RawItemGet(id), RawItemGet Get by RawSubCategoryid).");
            return Json(list);
        }

        [HttpGet]
        public async Task<IActionResult> WareHouseStoreDepartment()
        {
            // ViewBag.InventoryTypeEnum = new SelectList(_service.InventoryTypeEnumDropDown(), "Value", "Text");

            var vmUserDepartment = await _service.WareHouseStoreDepartmentGet();
            return View(vmUserDepartment);
        }
        [HttpPost]
        public async Task<IActionResult> WareHouseStoreDepartment(VMUserDepartment vmUserDepartment)
        {

            if (vmUserDepartment.ActionEum == ActionEnum.Add)
            {
                await _service.UserStoreDepartmentAdd(vmUserDepartment);

            }
            else if (vmUserDepartment.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.UserStoreDepartmentEdit(vmUserDepartment);
            }
            else if (vmUserDepartment.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.UserStoreDepartmentDelete(vmUserDepartment.ID);
            }

            else
            {
                return RedirectToAction("Error", "Home");
            }

            return RedirectToAction(nameof(WareHouseStoreDepartment));
        }

        [HttpGet]
        public async Task<IActionResult> WareHousePurchaseOrder()
        {
            var vmWareHousePOReceivingSlave = await _service.WareHousePurchaseOrderGet();
            return View(vmWareHousePOReceivingSlave);
        }
        [HttpGet]
        public async Task<IActionResult> WareHousePOSlaveReceivingDetailsByPO(int id)
        {
            VMWareHousePOReceivingSlave vmWareHousePOReceivingSlave = new VMWareHousePOReceivingSlave();
            if (id > 0)
            {
                vmWareHousePOReceivingSlave = await _service.WareHousePOSlaveReceivingDetailsByPOGet(id);
            }
            return View(vmWareHousePOReceivingSlave);
        }
        [HttpGet]
        public async Task<IActionResult> WareHousePOReceivingSlaveReport(int id = 0)
        {
            VMWareHousePOReceivingSlave vmWareHousePOReceivingSlave = new VMWareHousePOReceivingSlave();
            vmWareHousePOReceivingSlave = await _service.WareHousePOReceivingSlaveGet(id);

            vmWareHousePOReceivingSlave.TotalCostingPriceInWord = VmCommonCurrency.NumberToWords(Convert.ToDecimal(vmWareHousePOReceivingSlave.DataListSlave.Select(x => x.TotalCostingPrice).DefaultIfEmpty(0).Sum()), CurrencyType.BDT);


            return View(vmWareHousePOReceivingSlave);
        }
        [HttpGet]
        public async Task<IActionResult> WareHousePOReceivingSlave(int id = 0)
        {
            VMWareHousePOReceivingSlave vmWareHousePOReceivingSlave = new VMWareHousePOReceivingSlave();
            if (id == 0)
            {
                vmWareHousePOReceivingSlave = new VMWareHousePOReceivingSlave()
                {
                    ChallanDate = DateTime.Today
                    // ProcurementPurchaseOrderList = new SelectList(_service.PODropDownList(), "Value", "Text")
                };
            }
            else if (id > 0)
            {
                vmWareHousePOReceivingSlave = await _service.WareHousePOReceivingSlaveGet(id);
            }
            return View(vmWareHousePOReceivingSlave);
        }

        [HttpPost]
        public async Task<IActionResult> WareHousePOReceivingSlave(VMWareHousePOReceivingSlave vmModel, VMWareHousePOReceivingSlavePartial vmModelList)
        {
            if (vmModel.ActionEum == ActionEnum.Add)
            {
                if (vmModel.WareHouse_POReceivingFk == 0)
                {
                    vmModel.WareHouse_POReceivingFk = await _service.WareHousePOReceivingAdd(vmModel);
                }
                await _service.WareHousePOReceivingSlaveAdd(vmModel, vmModelList);
            }
            //else if (model.ActionEum == ActionEnum.Edit)
            //{
            //    //Edit
            //    await _service.ShipmentDeliveryChallanSlaveEdit(model);
            //}
            //else if (model.ActionEum == ActionEnum.Delete)
            //{
            //    //Delete
            //    await _service.ShipmentDeliveryChallanSlaveDelete(model.ID);
            //}

            else
            {
                return RedirectToAction("Error", "Home");
            }

            return RedirectToAction(nameof(WareHousePOReceivingSlave), new { id = vmModel.WareHouse_POReceivingFk });
        }
        [HttpGet]
        public async Task<IActionResult> WareHousePOSalesReturnListByPO(int id = 0)
        {
            VMWareHousePOReceivingSlave vmWareHousePOReceivingSlave = new VMWareHousePOReceivingSlave();
            vmWareHousePOReceivingSlave = await _service.WareHousePOSlaveReturnDetailsByPOGet(id);

            return View(vmWareHousePOReceivingSlave);
        }
        [HttpGet]
        public async Task<IActionResult> WareHouseProductReturnSlaveReport(int id = 0)
        {
            VMWareHousePOReturnSlave vmWareHousePOReturnSlave = new VMWareHousePOReturnSlave();
            vmWareHousePOReturnSlave = await _service.WareHouseProductReturnSlaveGet(id);

            return View(vmWareHousePOReturnSlave);
        }
        [HttpGet]
        public async Task<IActionResult> WareHouseReturnBySupplierList()
        {
            VMWareHousePOReturnSlave vmWareHousePOReturnSlave = new VMWareHousePOReturnSlave();
            vmWareHousePOReturnSlave = await _service.WareHouseProductReturnGet();

            return View(vmWareHousePOReturnSlave);
        }

        [HttpGet]
        public async Task<IActionResult> WareHousePOSalesReturnSlave(int id = 0)
        {
            VMWareHousePOReturnSlave vmWareHousePOReturnSlave = new VMWareHousePOReturnSlave();
            if (id == 0)
            {
                vmWareHousePOReturnSlave = new VMWareHousePOReturnSlave()
                {
                    ChallanDate = DateTime.Today,
                    //ProcurementPurchaseOrderList = new SelectList(_service.POForSalesReturnDropDownList(), "Value", "Text")

                };
            }
            else if (id > 0)
            {
                vmWareHousePOReturnSlave = await _service.WareHousePOSalseReturnSlaveGet(id);
            }
            return View(vmWareHousePOReturnSlave);
        }

        [HttpPost]
        public async Task<IActionResult> WareHousePOSalesReturnSlave(VMWareHousePOReturnSlave vmModel, VMWareHousePOReturnSlavePartial vmModelList)
        {

            if (vmModel.ActionEum == ActionEnum.Add)
            {
                if (vmModel.WareHouse_POReceivingFk > 0)
                {
                    vmModel.WareHouse_POReceivingFk = await _service.WareHousePOReturnAdd(vmModel);
                }
                else
                {
                    // to return causes
                    vmModel.WareHouse_POReceivingFk = await _service.WareHousePOReturnAdd(vmModel);
                }
                await _service.WareHousePOSalseReturnSlaveAdd(vmModel, vmModelList);
            }
            else
            {
                return RedirectToAction("Error", "Home");
            }

            return RedirectToAction(nameof(WareHousePOSalesReturnSlave), new { id = vmModel.WareHouse_POReceivingFk });
        }
        [HttpGet]
        public async Task<IActionResult> WareHouseProductReturnToSupplier(int id = 0)
        {
            VMWareHousePOReturnSlave vmWareHousePOReturnSlave = new VMWareHousePOReturnSlave();
            if (id > 0)

KG.Pos.App/Views/WareHouse/BazaarBakWareHouseRawItemInventory.cshtml
@using KG.Core.Services

@{

    ViewData["Title"] = " Inventory";
    Layout = "~/Views/Shared/_Layout.cshtml";


}
@model KG.Core.Services.Configuration.VMCommonProduct
<script src="~/bower_components/jquery/dist/jquery.min.js"></script>

<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>
<section class="content-header">
    <h1>
        Inventory
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active">Raw Materials Inventory</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("BazaarBakShopStockReport", "WareHouse", FormMethod.Post, new { id = "wareHouseRawItemInventoryformId", @class = "formValidator", @target = "_blank", @enctype = "multipart/form-data" }))
            {
                <div class="box">
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="box-danger">

                        <!-- /.box-header -->
                        <div class="box-body">

                            @Html.HiddenFor(model => model.ActionId, new { id = "ActionId" })

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Shop:</label>
                                        @Html.DropDownListFor(model => model.Common_ShopFK, Model.ShopList as SelectList, "==Select Shop==", new { id = "ddlCommon_ShopFK", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.Common_ShopFK, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Brand:</label>
                                        @Html.DropDownListFor(model => model.Common_BrandFk, Model.BrandList as SelectList, "---Select Brand---", new { id = "ddlCommon_BrandFk", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.Common_BrandFk, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Supplier:</label>
                                        @Html.DropDownListFor(model => model.Common_SupplierFk, Model.SupplierList as SelectList, "---Select Supplier---", new { id = "ddlCommon_SupplierFk", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.Common_SupplierFk, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">


                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Category:</label>
                                        @Html.DropDownListFor(model => model.Common_ProductCategoryFk, Model.ProductCategoryList as SelectList, "---Select Category---", new { id = "ddlCommon_ProductCategoryFk", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.Common_ProductCategoryFk, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Subcategory:</label>
                                        @Html.DropDownListFor(model => model.Common_ProductSubCategoryFk, Model.ProductSubCategoryList as SelectList, "---Select Subcategory---", new { id = "ddlCommonProductSubCategoryFk", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.Common_ProductSubCategoryFk, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Item:</label>
                                        @Html.DropDownListFor(model => model.ID, Model.ProductList as SelectList, "---Select Item---", new { id = "ddlCommonProductFk", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>


                            @*<input type="checkbox" asp-for="IsCategoryWise" name="IsCategoryWise" />  Category Wise*@


                        </div>
                        <div class="box-footer">
                            <div class="col-md-3">
                            </div>
                            <div class="col-md-9">
                                <div class="form-group">
                                    <div class="col-md-7">
                                        <select asp-for="ReportType" class="pull-right" style="color:#ffffff; background-color:#dd4b39;height:34px;font-size:15px;width:100%" name="ReportType" id="ddlReportType">
                                            <option value="PDF">PDF</option>
                                            <option value="EXCEL">EXCEL</option>
                                            <option value="WORD">WORD</option>
                                        </select>
                                    </div>
                                    <div class="col-md-5">
                                        <input style="width:100%" type="submit" name="EXPORT" value="EXPORT" class="btn btn-success pull-right" formtarget="_blank" />
                                    </div>


                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            }


        </div>

    </div>
</section>


@section scripts {

    <script type="text/javascript">


        $(document).ready(function () {

             //$('.formValidator').bootstrapValidator();

             $("#ddlCommon_ProductCategoryFk").change(function () {

                var productCategoryFk = $("#ddlCommon_ProductCategoryFk").val();
                     $.ajax({
                type: "GET",
                url: "@Url.Action("GetCommonProductSubCategory", "WareHouse")",
                datatype: "Json",
                         data: { id: productCategoryFk},
                    success: function (data) {
                    var items = "";
                        if (data) {
                            $("#ddlCommonProductSubCategoryFk").empty();
                            $("#ddlCommonProductSubCategoryFk").append("<option value=''>==Select Subcategory==</option>");
                            $(data).each(function (index, item) {
                                $("#ddlCommonProductSubCategoryFk").append("<option value='" + item.value + "'>" + item.text + "</option>");
                            });

                        }
                    }
                });
            })


            $("#ddlCommonProductSubCategoryFk").change(function () {

                var productSubCategoryFk = $("#ddlCommonProductSubCategoryFk").val();
                     $.ajax({
                type: "GET",
                url: "@Url.Action("GetCommonProduct", "WareHouse")",
                datatype: "Json",
                         data: {  id : productSubCategoryFk},
                    success: function (data) {
                    var items = "";
                        if (data) {
                            $("#ddlCommonProductFk").empty();
                            $("#ddlCommonProductFk").append("<option value=''>==Select Item==</option>");
                            $(data).each(function (index, item) {
                                $("#ddlCommonProductFk").append("<option value='" + item.value + "'>" + item.text + "</option>");
                            });

                        }
                    }
                });
            })





        });


        function resetForm() {
            $('#wareHouseRawItemInventoryformId')[0].reset();


        }
    </script>
}

KG.Pos.App/Views/WareHouse/WareHouseOrderItemConsumption.cshtml
@{
    ViewData["Title"] = "Store Out List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using KG.Core.Services;
@model KG.Core.Services.WareHouse.VMWareHouseConsumption
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>

    <section class="content-header">
        <h1>
            Store Out
            <small>List</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            @*<li><a href="~/Shipment/ShipmentInstructiones"></a></li>*@
            <li class="active"> Store Out List</li>
        </ol>
    </section>
    @using (Html.BeginForm("warehouseorderitemconsumption", "WareHouse", FormMethod.Post, new { id = "wareHouseProductionItemConsumptionFormId", @class = "formValidator" }))
    {
        <section class="content">
            <div class="row">
                <div class="box">
                    <div class="box-danger">
                        <div class="box-header">

                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <!--Body Will by Start Here-->
                            <div class="table-responsive text-nowrap">
                                <table id="tableX" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>SL</th>
                                            @*<td>Requisition ID</td>*@
                                            <th>Store Out Ref.</th>
                                            <th>Date</th>
                                            <th>Store out from</th>
                                            <th>Store out to</th>
                                            <th>Send By</th>
                                            <th>Shop Name</th>
                                            <th>Status</th>
                                            <th>Acknowledgement Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    @{int sl = 0;
                                    }
                                    <tbody>
                                        @foreach (var item in Model.ConsumptionDataList)
                                        {
                                        <tr>
                                            <td>@(++sl).</td>
                                            @*<td>
                                                <table>
                                                    @foreach (var subItem in item.RequisitionCIDList)
                                                    {
                                                        <tr>
                                                            <td>@subItem</td>
                                                        </tr>
                                                    }

                                                </table>
                                            </td>*@
                                            <td>
                                                <a target="_blank" href="~/WareHouse/WareHouseOrderItemConsumptionSlaveReport/@item.ID"> @item.ConsumptionCID</a>


                                            </td>
                                            <td>@item.Date.ToString("yyyy/MM/dd")</td>
                                            <td>@item.FromUserDepartmentName</td>
                                            <td>@item.ToUserDepartmentName</td>
                                            <td>@item.UserName</td>
                                            <td>@item.ShopName</td>

                                            <td>
                                                @if (item.Acknowledgement)
                                                {
                                                    <span class="label label-success">Acknowledge</span>
                                                }
                                                else
                                                {
                                                    <span class="label label-danger">Not Accept</span>

                                                }
                                            </td>
                                            <td>@item.AcknowledgementDate?.ToString("yyyy/MM/dd")</td>

                                            <td>
                                                @*<a onclick="makeAcknowledable(@item.ID);" class="linkPointer" data-toggle="modal" data-target="#acknowledgementModal" title="Acknowledgement" data-placement="top"><i class="fa fa-check" aria-hidden="true"></i></a>*@
                                                @if (item.SendByStoreRequisition)
                                                {
                                                    <a href="~/WareHouse/WareHouseOrderItemConsumptionSlave/@item.ID"><i class="glyphicon glyphicon-new-window"></i></a>
                                                }
                                                else
                                                {
                                                    <a href="~/WareHouse/WareHouseGeneralOrderItemConsumptionSlave/@item.ID"><i class="glyphicon glyphicon-new-window"></i></a>

                                                }
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="box-footer">

                        </div>
                    </div>
                </div>
            </div>
        </section>


        <div class="modal fade" id="acknowledgementModal" data-toggle="modal" data-backdrop="static" data-keyboard="false" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
                            &times;
                        </button>
                        <h5 class="modal-title"><b>Acknowledgement Store Out</b></h5>
                        @Html.HiddenFor(model => model.ID, new { Value = "", id = "hidWareHouseConsumptionId" })
                        @Html.HiddenFor(model => model.ActionId, new { Value = "", id = "ActionId" })
                    </div>
                    <div class="modal-body">
                        <div style="text-align:center">
                            <h3>Are you sure to Acknowledgement?</h3>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="btncloseandreset" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" id="btnsave" class="btn btn-primary">&nbsp;&nbsp;&nbsp;Acknowledgement</button>&nbsp;&nbsp;&nbsp;
                    </div>
                </div>
            </div>
        </div>
    }

    @section scripts {
        <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();
        });

        function makeAcknowledable(id) {
            if (id !== null) {
                $('#hidWareHouseConsumptionId').val(id);
                $('#ActionId').val(@((int)ActionEnum.Acknowledgement));

            }
        }


        </script>
    }