KG.Pos.App/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using KG.Core.Services;
using KG.Core.Services.Configuration;
using KG.Core.Services.Home;
using KG.Core.Services.User;
using KG.Infrastructure;
using System.Net;
using BarcodeLib;
using System.Drawing;
using System.IO;
using System.Drawing.Imaging;
using KG.Core.Services.Marketing;

namespace Pos.App.Controllers
{
    //[SoftwareAdmin]
    public class ConfigurationController : Controller
    {
        private readonly ILogger _logger;
        private IHostingEnvironment _webHostEnvironment;
        private HttpContext httpContext;
        private readonly ConfigurationService _service;
        private readonly VMLogin _vmLogin;

        public ConfigurationController(InfrastructureDbContext db, ILogger<ConfigurationController> logger, IHostingEnvironment webHostEnvironment, IHttpContextAccessor httpContextAccessor)
        {
            SessionHandler sessionHandler = new SessionHandler(db, httpContextAccessor.HttpContext);
            sessionHandler.Adjust();
            httpContext = httpContextAccessor.HttpContext;
            _webHostEnvironment = webHostEnvironment;
            _service = new ConfigurationService(db, httpContextAccessor.HttpContext);
            _logger = logger;
            _vmLogin = httpContextAccessor.HttpContext.Session.GetObjectFromJson<VMLogin>("LoginUser");
        }

        [HttpPost]
        public ActionResult CustomerRDLGet(VMCommonCustomer vMCommonCustomer)
        {
            NetworkCredential nwc = new NetworkCredential("Administrator", "Gocorona!9");
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/{0}&rs:Command=Render&rs:Format={1}", vMCommonCustomer.ReportName, vMCommonCustomer.ReportType);

            if (vMCommonCustomer.ReportType.Equals(ReportType.EXCEL))
            {
                return File(client.DownloadData(reportURL), "application/vnd.ms-excel", "ProdReference.xls");
            }
            if (vMCommonCustomer.ReportType.Equals(ReportType.PDF))
            {
                return File(client.DownloadData(reportURL), "application/pdf");

            }
            if (vMCommonCustomer.ReportType.Equals(ReportType.WORD))
            {
                return File(client.DownloadData(reportURL), "application/msword", "ProdReference.doc");
            }

            return View();

        }

        #region Unit
        public async Task<IActionResult> CommonUnit()
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            VMCommonUnit vmCommonUnit = new VMCommonUnit();
            vmCommonUnit = await Task.Run(() => _service.GetUnit());
            return View(vmCommonUnit);
        }
        public async Task<JsonResult> SingleCommonUnit(int id)
        {

            VMCommonUnit model = new VMCommonUnit();
            model = await _service.GetSingleCommonUnit(id);
            return Json(model);
        }
        [HttpPost]
        public async Task<IActionResult> CommonUnit(VMCommonUnit vmCommonUnit)
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            if (vmCommonUnit.ActionEum == ActionEnum.Add)
            {
                //Add 
                await _service.UnitAdd(vmCommonUnit);
            }
            else if (vmCommonUnit.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.UnitEdit(vmCommonUnit);
            }
            else if (vmCommonUnit.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.UnitDelete(vmCommonUnit.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(CommonUnit));
        }
        [HttpPost]
        public async Task<IActionResult> CommonUnitDelete(VMCommonUnit vmCommonUnit)
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            if (vmCommonUnit.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.UnitDelete(vmCommonUnit.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(CommonUnit));
        }
        [HttpPost]
        public async Task<IActionResult> CommonUnitLockUnlock(VMCommonUnit vmCommonUnit)
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            await _service.UnitLockUnlock(vmCommonUnit.ID);
            return RedirectToAction(nameof(CommonUnit));
        }
        #endregion

        #region Common Supplier


        public JsonResult CommonSupplierByIDGet(int id)
        {
            var model = _service.GetCommonSupplierByID(id);
            return Json(model);
        }


        public async Task<IActionResult> CommonSupplier()
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            VMCommonSupplier vmCommonSupplier = new VMCommonSupplier();
            vmCommonSupplier = await Task.Run(() => _service.GetSupplier());
            //vmCommonSupplier.CountryList = new SelectList(_service.CommonCountriesDropDownList(), "Value", "Text");
            vmCommonSupplier.DistrictList = new SelectList(_service.CommonDistrictsDropDownList(), "Value", "Text");
            vmCommonSupplier.DivisionList = new SelectList(_service.CommonDivisionsDropDownList(), "Value", "Text");

            vmCommonSupplier.ThanaList = new SelectList(_service.CommonThanaDropDownList(), "Value", "Text");


            return View(vmCommonSupplier);
        }
        [HttpPost]
        public async Task<IActionResult> CommonSupplier(VMCommonSupplier vmCommonSupplier)
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            if (vmCommonSupplier.ActionEum == ActionEnum.Add)
            {
                //Add 
                await _service.SupplierAdd(vmCommonSupplier);
            }
            else if (vmCommonSupplier.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.SupplierEdit(vmCommonSupplier);
            }
            else if (vmCommonSupplier.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.SupplierDelete(vmCommonSupplier.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(CommonSupplier));
        }
        [HttpPost]
        public async Task<IActionResult> CommonSupplierDelete(VMCommonSupplier vmCommonSupplier)
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            if (vmCommonSupplier.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.SupplierDelete(vmCommonSupplier.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(CommonSupplier));
        }



        #endregion

        #region Common Product Category
        public async Task<JsonResult> SingleProductCategory(int id)
        {
            var model = await _service.GetSingleProductCategory(id);
            return Json(model);
        }
        public async Task<IActionResult> CommonProductCategory()
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            VMCommonProductCategory vmCommonProductCategory = new VMCommonProductCategory();
            vmCommonProductCategory = await Task.Run(() => _service.GetProductCategory());
            return View(vmCommonProductCategory);
        }
        [HttpPost]
        public async Task<IActionResult> CommonProductCategory(VMCommonProductCategory vmCommonProductCategory)
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            if (vmCommonProductCategory.ActionEum == ActionEnum.Add)
            {
                //Add 
                await _service.ProductCategoryAdd(vmCommonProductCategory);
            }
            else if (vmCommonProductCategory.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.ProductCategoryEdit(vmCommonProductCategory);
            }
            else if (vmCommonProductCategory.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.ProductCategoryDelete(vmCommonProductCategory.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(CommonProductCategory));
        }
        [HttpPost]
        public async Task<IActionResult> CommonProductCategoryDelete(VMCommonProductCategory vmCommonProductCategory)
        {
            if (_vmLogin == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            if (vmCommonProductCategory.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.ProductCategoryDelete(vmCommonProductCategory.ID);
            }

KG.Pos.App/Views/Configuration/ChangeProductMRPPrice.cshtml
@{
    ViewData["Title"] = "Change Product MRP Price";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string collapsedBox = "";

}
@model KG.Core.Services.Configuration.VMCommonProduct
<script src="~/bower_components/jquery/dist/jquery.min.js"></script>

<section class="content-header">
    <h1>
        <span>
            Change Product MRP Price
        </span>


    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>

        <li class="active"> Change Product MRP Price</li>
    </ol>
</section>
@using (Html.BeginForm("ChangeProductCostingPrice", "Configuration", FormMethod.Post, new { id = "changeProductCostingPriceFormId", @class = "formValidator" }))
{
    <section class="content">
        <div class="row">
            <div class="box">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="box-danger">
                    <div class="box-header">

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="box box-success box-solid @collapsedBox">
                                <div class="box-header with-border">
                                    <h3 class="box-title" style="text-align:center">
                                        Change Product Costing Price
                                    </h3>
                                    <div class="box-tools pull-right">
                                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                </div>
                                @Html.HiddenFor(model => model.ActionId, new { id = "changeProductExpiryActionId" })

                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-md-1"></div>
                                        <div class="col-md-10">

                                            <div class="box-body">
                                                <div class="form-group">
                                                    <label>Search By Product or Barcode</label>
                                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @autocomplete = "on", @class = "form-control", @name = "ProductName", @id = "txtProductNameOrBarcode" } })
                                                    @Html.HiddenFor(model => model.ID, new { id = "hidCommon_ProductFK" })

                                                    @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                                                </div>

                                            </div>
                                            <div class="box-body">

                                                <table id="productDetailsTable" class="table">
                                                    <tr>
                                                        <th>
                                                            Category
                                                        </th>
                                                        <td><span id="spnCategoryName"></span></td>
                                                        <th>
                                                            Subcategory
                                                        </th>
                                                        <td><span id="spnSubCategoryName"></span></td>
                                                    </tr>
                                                    <tr>
                                                        <th>MRP Price</th>
                                                        <td>
                                                            <span id="spnMRPPrice"></span>
                                                        </td>
                                                        <th>
                                                            Current Expiry Date
                                                        </th>
                                                        <td><span id="spnExpiryDate"></span></td>
                                                    </tr>
                                                    <tr>
                                                        <th>VAT</th>
                                                        <td>

                                                            <span id="spnVAT"></span>
                                                        </td>
                                                        <th>
                                                            Unit
                                                        </th>
                                                        <td>
                                                            <span id="spnUnitName"></span>
                                                        </td>
                                                    </tr>
                                                    <tr>

                                                        <th>
                                                            Costing Price
                                                        </th>
                                                        <td>
                                                            <input name="CostingPrice" asp-for="CostingPrice" type="text" required="required" class="form-control" id="txtCostingPrice" placeholder="CostingPrice" autocomplete="off">
                                                        </td>
                                                        <th>
                                                            MRP Price
                                                        </th>
                                                        <td>
                                                            <input name="MRPPrice" asp-for="MRPPrice" type="text" required="required" class="form-control" id="txMRPPrice" placeholder="MRP Price" autocomplete="off">
                                                        </td>
                                                    </tr>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-1"></div>

                                </div>
                                <div class="box-footer">
                                    @if (Model.ID > 0)
                                    {
                                        <h4 class="text-success text-center">
                                            The MRP Price of<span class="text-danger"> @Model.Name @Model.SystemBarcode</span> Successfully Changed with <span class="text-danger">@Model.MRPPrice</span>
                                        </h4>
                                    }
                                    <div class="row">
                                        <div class="col-md-4">

                                        </div>
                                        <div class="col-lg-8 col-md-8">
                                            <button type="submit" id="btnsave" class="btn btn-primary btn-block">
                                                <i class='fa fa-edit'></i>

                                                <span>Change</span>

                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">

                    </div>
                </div>
            </div>
        </div>
    </section>


}


@section scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();
            $("#productDetailsTable").hide();



 $("#txtProductNameOrBarcode").autocomplete({
                source: function (request, response) {
                    //console.log(request);
                    //console.log(response);

                    $.ajax({
                        url:"@Url.Action("AutoCompleteProductGet", "Marketing")",// '/AccountHeads/AutoComplete/',
                        //data: "{ 'prefix': '" + request.term + "'}",
                        data: { id : request.term },
                        dataType: "json",
                        type: "get",
                        cache: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            //alert(response.responseText);
                        },
                        failure: function (response) {
                            //alert(response.responseText);
                        }
                    });
                },

                select: function (e, i) {
                    $("#hidCommon_ProductFK").val(i.item.val);

                   $.ajax({
                    type: "POST",
                    url: "@Url.Action("CommonProductByID", "Configuration")",
                    datatype: "Json",
                       data: { id: i.item.val },
                     success: function (data) {
                         console.log(data);
                         $("#productDetailsTable").show();
                         $("#txtCostingPrice").val(data.costingPrice)
                         $("#txMRPPrice").val(data.mrpPrice);
                         $("#spnCategoryName").text(data.categoryName);
                         $("#spnSubCategoryName").text(data.subCategoryName);
                         $("#spnMRPPrice").text(data.mrpPrice);
                         $("#spnVAT").text(data.vat);
                         $("#spnUnitName").text(data.unitName);

                         var expiryDate = data.expiryDate;
                         $("#spnExpiryDate").text(expiryDate.substr(0, 10));
                         $("#txtExpiryDate").val(expiryDate.substr(0, 10));
                         $("#changeProductExpiryActionId").val(2)
                    }
                });
     },
     autoFocus: true,
                minLength: 1,
                cache: true

            }).focus(function () {
                $(this).autocomplete("search");
            });


            @*$.ajaxSetup({ cache: false });
            //$("#ddlShipmentInvoiceFk").change(function (e) {
            $("#ddlProductId").change(function (e) {
                var productId = $("#ddlProductId").val();

                 $.ajax({
                    type: "POST",
                    url: "@Url.Action("CommonProductByID", "Configuration")",
                    datatype: "Json",
                     data: { id: productId },
                     success: function (data) {
                         console.log(data);
                         $("#productDetailsTable").show();
                         $("#txtCostingPrice").val(data.costingPrice)
                         $("#txMRPPrice").val(data.mrpPrice);
                         $("#spnCategoryName").text(data.categoryName);
                         $("#spnSubCategoryName").text(data.subCategoryName);
                         $("#spnMRPPrice").text(data.mrpPrice);
                         $("#spnVAT").text(data.vat);
                         $("#spnUnitName").text(data.unitName);

                         var expiryDate = data.expiryDate;
                         $("#spnExpiryDate").text(expiryDate.substr(0, 10));
                         $("#txtExpiryDate").val(expiryDate.substr(0, 10));
                         $("#changeProductExpiryActionId").val(2)
                    }
                });


                return false;
             });*@
        });



    </script>
}

KG.Pos.App/Views/Configuration/CommonProductBarcodeGenerateView.cshtml
@using KG.Core.Services;


@model KG.Core.Services.Configuration.VMCommonProduct

@{
    Layout = null;

    int lastTdQuantity = 5;
    int LastData = Model.DataToListProduct.Count();
    int loopCount = LastData / 5;

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title> Make Product Barcode</title>
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">


    <style type="text/css">
        body {
            width: 100%;
            height: 100%;
            margin: 3px 0 0 0;
            text-align: center;
        }

        * {
            box-sizing: border-box;
            -moz-box-sizing: border-box;
        }

        .trClass {
            height: 22.84px;
            min-height: 22.84px;
            max-height: 22.84px;
        }

        .page {
            width: 210mm;
            min-height: 297mm;
        }

        @@page {
            size: A4;
            margin: 3px 0 0 0;
        }

        @@media print {
            html, body {
                width: 210mm;
                height: 297mm;
            }

            #printPageButton {
                display: none;
            }

            .trClass {
                height: 22.84px;
                min-height: 22.84px;
                max-height: 22.84px;
            }

            .page {
                margin: 0;
            }
        }
    </style>


</head>


<body>
    <button id="printPageButton" type="button" style="float: right; position: fixed;right: 0; vertical-align: top; " onclick="printDiv()" class="btn btn-default">
        Print
    </button>

    <div class="page text-center box-info">
        <table style="width:100%">
            @for (int totalQuantity = 0; totalQuantity < Model.DataToListProduct.Count(); totalQuantity++)
            {
                loopCount--;
                <tr class="trClass">
                    
                    @for (int rowQuantity = 0; rowQuantity < lastTdQuantity; rowQuantity++)
                    {
                        <td style="width:20%;border:dotted 1px lightgray;min-height:90px">
                            <span style="text-align:center;font-weight:bold;font-size:10px;padding-bottom:0px">
                                @Model.DataToListProduct[totalQuantity].SubCategoryName @Model.DataToListProduct[totalQuantity].Name
                            </span>

                            <img id="barcodeImge" src="@Url.Action("GenerateBarcode", "Configuration", new { id = Model.DataToListProduct[totalQuantity].ID})" alt="Barcode" />
                            <span style="text-align:center;font-size:12px">
                                <b>
                                    MRP  @Model.DataToListProduct[totalQuantity].MRPPrice TK +VAT
                                </b>
                            </span>
                        </td>


                        totalQuantity += rowQuantity > 0 ? 1 : 0;
                        LastData--;
                    }
                </tr>
                if (loopCount == 0)
                {
                    lastTdQuantity = LastData;
                }
            }

        </table>
    </div>

    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="~/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/dist/js/adminlte.min.js"></script>

    <script src="~/jQueryScannerDetection/jquery.scannerdetection.js"></script>

    <script type="text/javascript">
        function printDiv() {
            window.print();
        }
    </script>


</body>


</html>