KG.Pos.App/Controllers/ProcurementController.cs
using KG.Core.Services;
using KG.Core.Services.Configuration;
using KG.Core.Services.Home;
using KG.Core.Services.Procurement;
using KG.Core.Services.User;
using KG.Infrastructure;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace KG.App.Controllers
{
    //[SoftwareAdmin]
    public class ProcurementController : Controller
    {
        private readonly ILogger _logger;
        private readonly ProcurementService _service;
        private readonly HttpContext _httpContext;
        private readonly VMLogin _vMLogin;
        public ProcurementController(InfrastructureDbContext db, IHttpContextAccessor httpContextAccessor, ILogger<ProcurementController> logger, IDataProtectionProvider provider)
        {
            SessionHandler sessionHandler = new SessionHandler(db, httpContextAccessor.HttpContext);
            sessionHandler.Adjust();
            _vMLogin = httpContextAccessor.HttpContext.Session.GetObjectFromJson<VMLogin>("LoginUser");
            _httpContext = httpContextAccessor.HttpContext;
            _service = new ProcurementService(db, httpContextAccessor.HttpContext);
            _logger = logger;
        }



        #region Purchase Requisition
        [HttpGet]
        public async Task<IActionResult> ProcurementPurchaseRequisitionSlave(int id = 0)
        {
            VMPurchaseRequisitionSlave vmPurchaseRequisitionSlave = new VMPurchaseRequisitionSlave();
            if (id == 0)
            {
                vmPurchaseRequisitionSlave.Status = (int)EnumPRStatus.Draft;
            }
            else if (id > 0)
            {
                vmPurchaseRequisitionSlave = await _service.ProcurementPurchaseRequisitionGetByID(id);
                vmPurchaseRequisitionSlave.DataListSlave = await _service.ProcurementPurchaseRequisitionSlaveGet(id);
            }
            //vmPurchaseRequisitionSlave.ProductCategorySelectList = new SelectList(_service.ProductCategoryDropDownList(), "Value", "Text");
            //vmPurchaseRequisitionSlave.ProductSubCategorySelectList = new SelectList(_service.ProductSubCategoryDropDownList(), "Value", "Text");
            //vmPurchaseRequisitionSlave.ProductSelectList = new SelectList(_service.ProductDropDownList(), "Value", "Text");
            return View(vmPurchaseRequisitionSlave);
        }

        [HttpPost]
        public async Task<IActionResult> ProcurementPurchaseRequisitionSlave(VMPurchaseRequisitionSlave vmPurchaseRequisitionSlave)
        {

            if (vmPurchaseRequisitionSlave.ActionEum == ActionEnum.Add)
            {
                if (vmPurchaseRequisitionSlave.Procurement_PurchaseRequisitionFK == 0)
                {
                    vmPurchaseRequisitionSlave.Procurement_PurchaseRequisitionFK = await _service.ProcurementPurchaseRequisitionAdd(vmPurchaseRequisitionSlave);

                }
                await _service.ProcurementPurchaseRequisitionSlaveAdd(vmPurchaseRequisitionSlave);
            }
            else if (vmPurchaseRequisitionSlave.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.ProcurementPurchaseRequisitionSlaveEdit(vmPurchaseRequisitionSlave);
            }
            else if (vmPurchaseRequisitionSlave.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.ProcurementPurchaseRequisitionSlaveDelete(vmPurchaseRequisitionSlave.ID);
            }
            //else if ((int)vmPurchaseRequisitionSlave.ActionEum > 3 && vmPurchaseRequisitionSlave.Procurement_PurchaseRequisitionFK > 0)
            //{
            //    //Delete
            //    await _service.PurchaseRequisitionStatusUpdate(new VMPurchaseRequisition() { User = sUser, ID = model.Procurement_PurchaseRequisitionFK, ActionId = (int)model.ActionEum, PRActionId = model.PRActionId, Description = model.Description });
            //}
            //else
            //{
            //    _logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + " (PurchaseRequisitionAdd,PRSlaveAdd) / PRSlaveEdit / PRSlaveDelete / PurchaseRequisitionStatusUpdate, Regular PR Functionalities failed).");
            //    return RedirectToAction("Error", "Home");
            //}
            //_logger.LogInformation("--From: " + ControllerContext.ActionDescriptor.ActionName + " (PurchaseRequisitionAdd,PRSlaveAdd) / PRSlaveEdit / PRSlaveDelete / PurchaseRequisitionStatusUpdate, Regular PR Functionalities).");
            return RedirectToAction(nameof(ProcurementPurchaseRequisitionSlave), new { id = vmPurchaseRequisitionSlave.Procurement_PurchaseRequisitionFK });
        }
        [HttpPost]
        public async Task<IActionResult> DeleteProcurementPurchaseRequisitionSlave(VMPurchaseRequisitionSlave vmPurchaseRequisitionSlave)
        {
            if (vmPurchaseRequisitionSlave.ActionEum == ActionEnum.Delete)
            {
                //Delete
                vmPurchaseRequisitionSlave.Procurement_PurchaseRequisitionFK = await _service.ProcurementPurchaseRequisitionSlaveDelete(vmPurchaseRequisitionSlave.ID);
            }
            return RedirectToAction(nameof(ProcurementPurchaseRequisitionSlave), new { id = vmPurchaseRequisitionSlave.Procurement_PurchaseRequisitionFK });
        }

        [HttpGet]
        public async Task<IActionResult> ProcurementPOStatusInPRPurchaseRequisitionList()
        {
            VMPurchaseRequisition vmPurchaseRequisition = new VMPurchaseRequisition();
            vmPurchaseRequisition = await _service.ProcurementPOStatusInPRPurchaseRequisitionListGet();

            return View(vmPurchaseRequisition);
        }



        [HttpGet]
        public async Task<IActionResult> ProcurementPurchaseRequisitionList()
        {
            VMPurchaseRequisition vmPurchaseRequisition = new VMPurchaseRequisition();
            vmPurchaseRequisition = await _service.ProcurementPurchaseRequisitionListGet();

            return View(vmPurchaseRequisition);
        }

        [HttpPost]
        public async Task<IActionResult> ProcurementPurchaseRequisitionList(VMPurchaseRequisition vmPurchaseRequisition)
        {

            if (vmPurchaseRequisition.ActionEum == ActionEnum.Edit)
            {

                await _service.ProcurementPurchaseRequisitionEdit(vmPurchaseRequisition);
            }

            return RedirectToAction(nameof(ProcurementPurchaseRequisitionList));
        }
        [HttpGet]
        public async Task<IActionResult> ProcurementClosedPurchaseRequisitionList()
        {
            VMPurchaseRequisition vmPurchaseRequisition = new VMPurchaseRequisition();
            vmPurchaseRequisition = await _service.ProcurementClosedPurchaseRequisitionListGet();

            return View(vmPurchaseRequisition);
        }
        [HttpGet]
        public async Task<IActionResult> ProcurementHoldPurchaseRequisitionList()
        {
            VMPurchaseRequisition vmPurchaseRequisition = new VMPurchaseRequisition();
            vmPurchaseRequisition = await _service.ProcurementHoldPurchaseRequisitionListGet();

            return View(vmPurchaseRequisition);
        }
       
        [HttpGet]
        public async Task<IActionResult> ProcurementCancelPurchaseRequisitionList()
        {
            VMPurchaseRequisition vmPurchaseRequisition = new VMPurchaseRequisition();
            vmPurchaseRequisition = await _service.ProcurementCancelPurchaseRequisitionListGet();

            return View(vmPurchaseRequisition);
        }

       
        [HttpGet]
        public async Task<IActionResult> ProcurementPurchaseRequisitionReport(int id = 0)
        {
            VMPurchaseRequisitionSlave vmPurchaseRequisitionSlave = new VMPurchaseRequisitionSlave();
            if (id > 0)
            {
                vmPurchaseRequisitionSlave = await _service.ProcurementPurchaseRequisitionGetByID(id);
                vmPurchaseRequisitionSlave.DataListSlave = await _service.ProcurementPurchaseRequisitionSlaveGet(id);
            }
            return View(vmPurchaseRequisitionSlave);
        }

        [HttpGet]
        public async Task<IActionResult> PurchaseRequisitionSummery(int id = 0)
        {
            VMPurchaseRequisitionSlave vmPurchaseRequisitionSlave = new VMPurchaseRequisitionSlave();
            if (id > 0)
            {
                vmPurchaseRequisitionSlave = await _service.ProcurementPurchaseRequisitionGetByID(id);
                vmPurchaseRequisitionSlave.DataListSlave = await _service.PurchaseRequisitionSummeryGet(id);
            }
            return View(vmPurchaseRequisitionSlave);
        }

        [HttpGet]
        public async Task<IActionResult> ProcurementStockDetailsByProduct(int id = 0)
        {
            VMCommonProduct vmCommonProduct = new VMCommonProduct();
            if (id > 0)
            {
                vmCommonProduct = await _service.CommonProductSingle(id);
                vmCommonProduct.DataList = await _service.ProcurementStockDetailsByProductGet(id);
            }
            return View(vmCommonProduct);
        }
        

        public async Task<JsonResult> SingleProcurementPurchaseRequisitionSlave(int id)
        {
            VMPurchaseRequisitionSlave model = new VMPurchaseRequisitionSlave();
            model = await _service.GetSingleProcurementPurchaseRequisitionSlave(id);
            return Json(model);
        }

        public async Task<JsonResult> SingleProcurementPurchaseRequisition(int id)
        {
            VMPurchaseRequisition model = new VMPurchaseRequisition();
            model = await _service.GetSingleProcurementPurchaseRequisition(id);
            return Json(model);
        }

        public JsonResult AutoCompletePRGet(string id)
        {

KG.Pos.App/Views/Procurement/ProcurementCancelPurchaseOrderList.cshtml
@using KG.Core.Services;
@model KG.Core.Services.Procurement.VMPurchaseOrder
@{
    ViewData["Title"] = "Cancel Purchase Order List";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int sl = 0;
}
<script src="~/bower_components/jquery/dist/jquery.min.js"></script>

<section class="content-header">
    <h1>
        <span>
            Cancel Purchase Order List
        </span>

    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active">Cancel Purchase Order</li>
    </ol>
</section>
@using (Html.BeginForm("ProcurementPurchaseOrderList", "Procurement", FormMethod.Post, new { id = "procurementPurchaseOrderListFormId", @class = "formValidator" }))
{
    <section class="content">
        <div class="row">
            <div class="box">
                <div class="box-danger">
                    <div class="box-header">

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="table-responsive col-md-12  text-nowrap">
                            <table id="tableRowSelect" class="table table-striped" width="100%">
                                <thead>
                                    <tr>
                                        <th>SL</th>
                                        <th>PO NO</th>
                                        <th>Order Date</th>

                                        <th>Payment Method</th>

                                        <th>User</th>
                                        <th>Supplier</th>
                                        <th>Status</th>
                                        <th>Description</th>

                                        <th>Delivery Date</th>
                                        <th>Delivery Address</th>
                                        <th>Total PO Value</th>

                                        <th>Details</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.DataList)
                                    {
                                        #region Link Title
                                        string cancelRenewTitle = "";

                                        ///////////////////////
                                        if (item.IsCancel)
                                        { cancelRenewTitle = "Make Renew"; }
                                        else
                                        { cancelRenewTitle = "Make Cancel"; }


                                        #endregion

                                        <tr>
                                            <th>@(++sl)</th>
                                            <td>@item.CID</td>
                                            <td>@item.OrderDate.ToString("dd-MM-yyyy")</td>


                                            <td>@item.POPaymentMethodName</td>

                                            <td>@item.User</td>
                                            <td>@item.SupplierName</td>
                                            <td>@item.EnumStatusName</td>
                                            <td>@item.Description</td>

                                            <td>@item.DeliveryDate?.ToString("dd-MM-yyyy")</td>
                                            <td>@item.DeliveryAddress</td>
                                            <td>@item.TotalPOValue</td>


                                            <td><a target="_blank" href="~/Procurement/ProcurementPurchaseOrderReport/@item.ID" title="Details"><i class="glyphicon glyphicon-new-window"></i></a></td>
                                            <td>

                                                <a id="@item.ID" onclick="makCancelable(@item.ID)" class="linkPointer" data-toggle="modal" data-target="#cancelRenewProcurementPurchaseOrderModal" title="@cancelRenewTitle" data-placement="top">
                                                    @if (item.IsCancel)
                                                    {<i class="glyphicon glyphicon-folder-open"></i> }
                                                    else
                                                    {<i class="fa fa-ban"></i>}
                                                </a>

                                            </td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="box-footer">
                        @*@if (Model.ID > 0)
                            {
                                <a target="_blank" href="~/Shipment/DeliveryChallanePrint/@Model.ID" class="btn btn-primary" style="width:100%">Print</a>
                            }*@
                    </div>
                </div>
            </div>
        </div>
    </section>


}

<form asp-action="CancelRenewProcurementPurchaseOrder" asp-controller="Procurement">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="modal fade" id="cancelRenewProcurementPurchaseOrderModal" data-toggle="modal" data-backdrop="static" data-keyboard="false" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
                        &times;
                    </button>
                    <h5 class="modal-title"><b><span class="cancelRenewText"></span> Purchase Order (<span id="cancelRenewPOCIDText"></span>)</b></h5>
                </div>
                <div class="modal-body">
                    @Html.HiddenFor(model => model.ID, new { id = "hidcancelRenewProcurementPurchaseOrderId" })
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div style="text-align:center">
                        <h3>Are you sure to <span class="cancelRenewText"></span> this Purchase Order?</h3>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-3">
                        <button type="button" onclick="resetProcurementPurchaseOrderForm()" class="btn btn-warning fa fa-close" data-dismiss="modal">&nbsp;NO</button>
                    </div>
                    <div class="col-md-9">
                        <button type="submit" id="btnHoldOrUnhold" style="width:100%" class="btn btn-primary">&nbsp;<span class="cancelRenewText"></span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section scripts {

    <script type="text/javascript">



            function makCancelable(rowId) {
                console.log(rowId);
                 $.ajax({
                        type: "POST",
                        url: "@Url.Action("SingleProcurementPurchaseOrder", "Procurement")",
                        datatype: "Json",
                        data: { id: rowId },
                        success: function (data) {
                            console.log(data);
                            $('#cancelRenewPOCIDText').text(data.cid);

                            if (data.isCancel == true) {
                                $('.cancelRenewText').text("Renew");
                            }
                            else {
                                $('.cancelRenewText').text("Cancel");

                            }
                        }
                 });
                $('#hidcancelRenewProcurementPurchaseOrderId').val(rowId);
            }


    </script>
}

KG.Pos.App/Views/Procurement/ProcurementCancelPurchaseRequisitionList.cshtml
@using KG.Core.Services;
@model KG.Core.Services.Procurement.VMPurchaseRequisition
@{
    ViewData["Title"] = "Cancel Purchase Requisition List";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int sl = 0;
    string cancelRenewTitle = "";
}
<script src="~/bower_components/jquery/dist/jquery.min.js"></script>

<section class="content-header">
    <h1>
        <span>
            Cancel Purchase Requisition List
        </span>

    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active">Cancel Purchase Requisition</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="box">
            <div class="box-danger">
                <div class="box-header"></div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive col-md-12  text-nowrap">
                        <table id="tableRowSelect" class="table table-striped" width="100%">
                            <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Requisition CID</th>
                                    <th>Requisition Date</th>
                                    <th>From</th>
                                    <th>To</th>
                                    <th>Requiste By</th>
                                    <th>Requisition Type</th>
                                    <th>Status</th>

                                    <th>PO Status</th>
                                    <th>Remarks</th>

                                    <th>Details</th>
                                    <th>Renew</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.DataList)
                                {
                                    #region Link Title

                                    if (item.IsCancel)
                                    { cancelRenewTitle = "Make Renew"; }
                                    else
                                    { cancelRenewTitle = "Make Cancel"; }
                                    #endregion

                                    <tr>
                                        <th>@(++sl)</th>
                                        <td>@item.RequisitionCID</td>
                                        <td>@item.RequisitionDate.ToString("dd-MM-yyyy")</td>

                                        <td>@item.FromUserDepartmentName</td>
                                        <td>@item.ToUserDepartmentName</td>
                                        <td>@item.User</td>


                                        <td>@item.EnumStatusName</td>

                                        <td>@item.POStatusInPRName</td>
                                        <td>@item.RequisitionRemarks</td>

                                        <td>
                                            <a href="~/Procurement/ProcurementPurchaseRequisitionSlave/@item.ID"><i class="glyphicon glyphicon-new-window"></i></a>

                                        </td>
                                        <td>
                                            <a id="@item.ID" onclick="makCancelable(@item.ID)" class="linkPointer" data-toggle="modal" data-target="#cancelRenewProcurementPurchaseRequisitionModal" title="@cancelRenewTitle" data-placement="top">
                                                @if (item.IsCancel)
                                                {<i class="glyphicon glyphicon-folder-open"></i> }
                                                else
                                                {<i class="fa fa-ban"></i>}
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="box-footer">
                    @*@if (Model.ID > 0)
                        {
                            <a target="_blank" href="~/Shipment/DeliveryChallanePrint/@Model.ID" class="btn btn-primary" style="width:100%">Print</a>
                        }*@
                </div>
            </div>
        </div>
    </div>
</section>

<form asp-action="CancelRenewProcurementPurchaseRequisition" asp-controller="Procurement">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="modal fade" id="cancelRenewProcurementPurchaseRequisitionModal" data-toggle="modal" data-backdrop="static" data-keyboard="false" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
                        &times;
                    </button>
                    <h5 class="modal-title"><b><span class="cancelRenewText"></span> Purchase Requisition (<span id="cancelRenewPRCIDText"></span>)</b></h5>
                </div>
                <div class="modal-body">
                    @Html.HiddenFor(model => model.ID, new { id = "hidcancelRenewProcurementPurchaseRequisitionId" })
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div style="text-align:center">
                        <h3>Are you sure to <span class="cancelRenewText"></span> this Purchase Requisition?</h3>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-3">
                        <button type="button" onclick="resetProcurementPurchaseRequisitionForm()" class="btn btn-warning fa fa-close" data-dismiss="modal">&nbsp;NO</button>
                    </div>
                    <div class="col-md-9">
                        <button type="submit" id="btnHoldOrUnhold" style="width:100%" class="btn btn-primary">&nbsp;<span class="cancelRenewText"></span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section scripts {

    <script type="text/javascript">


         function makCancelable(rowId) {
                console.log(rowId);
                 $.ajax({
                        type: "POST",
                        url: "@Url.Action("SingleProcurementPurchaseRequisition", "Procurement")",
                        datatype: "Json",
                        data: { id: rowId },
                        success: function (data) {
                            console.log(data);
                            $('#cancelRenewPRCIDText').text(data.requisitionCID);

                            if (data.isCancel == true) {
                                $('.cancelRenewText').text("Renew");
                            }
                            else {
                                $('.cancelRenewText').text("Cancel");

                            }
                        }
                 });
                $('#hidcancelRenewProcurementPurchaseRequisitionId').val(rowId);
            }

    </script>
}

KG.Pos.App/Views/Procurement/ProcurementPOStatusInPRPurchaseRequisitionList.cshtml
@using KG.Core.Services;
@model KG.Core.Services.Procurement.VMPurchaseRequisition
@{
    ViewData["Title"] = "Purchase Requisition List (Full PO Created)";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int sl = 0;
    string holdUnholdTitle = "";
}
<script src="~/bower_components/jquery/dist/jquery.min.js"></script>

<section class="content-header">
    <h1>
        <span>
            Purchase Requisition List (Full PO Created)
        </span>
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active">Purchase Requisition List (Full PO Created)</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="box">
            <div class="box-danger">
                <div class="box-header"></div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive col-md-12  text-nowrap">
                        <table id="tableRowSelect" class="table table-striped" width="100%">
                            <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Requisition CID</th>
                                    <th>Requisition Date</th>
                                    <th>From</th>
                                    <th>To</th>
                                    <th>Requiste By</th>

                                    <th>Status</th>

                                    <th>PO Status</th>
                                    <th>Remarks</th>

                                    <th>Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.DataList)
                                {


                                    <tr>
                                        <th>@(++sl)</th>
                                        <td>@item.RequisitionCID</td>
                                        <td>@item.RequisitionDate.ToString("dd-MM-yyyy")</td>

                                        <td>@item.FromUserDepartmentName</td>
                                        <td>@item.ToUserDepartmentName</td>
                                        <td>@item.User</td>


                                        <td>@item.EnumStatusName</td>


                                        <th>@item.POStatusInPRName</th>
                                        <td>@item.RequisitionRemarks</td>

                                        <td>
                                            <a href="~/Procurement/ProcurementPurchaseRequisitionSlave/@item.ID"><i class="glyphicon glyphicon-new-window"></i></a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="box-footer">
                    @*@if (Model.ID > 0)
                        {
                            <a target="_blank" href="~/Shipment/DeliveryChallanePrint/@Model.ID" class="btn btn-primary" style="width:100%">Print</a>
                        }*@
                </div>
            </div>
        </div>
    </div>
</section>