KG.Pos.App/Controllers/MarketingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using KG.Core.Services;
using Microsoft.AspNetCore.Http;
using KG.Core.Services.User;
using KG.Infrastructure;
using KG.Core.Services.Home;
using System.Reflection;
using System.Linq;
using System;
using KG.Core.Services.Configuration;
using KG.Core.Services.Marketing;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using KG.Core.Services.Procurement;
using System.Net;

namespace KG.App.Controllers
{
    //[SoftwareAdmin]
    public class MarketingController : Controller
    {
        private ILogger<MarketingController> _logger;
        private MarketingSaleService _service;
        private ConfigurationService _configurationService;
        private readonly VMLogin _vmLogin;


        public MarketingController(InfrastructureDbContext db, ILogger<MarketingController> logger, IHttpContextAccessor httpContextAccessor)
        {
            SessionHandler sessionHandler = new SessionHandler(db, httpContextAccessor.HttpContext);
            sessionHandler.Adjust();
            _service = new MarketingSaleService(db, httpContextAccessor.HttpContext);
            _configurationService = new ConfigurationService(db, httpContextAccessor.HttpContext);
            _logger = logger;
            _vmLogin = httpContextAccessor.HttpContext.Session.GetObjectFromJson<VMLogin>("LoginUser");

        }
        [HttpGet]
        public async Task<IActionResult> MarketingSalesReport()
        {
            VMMarketingSalesReport vmMarketingSalesReport = new VMMarketingSalesReport();
            vmMarketingSalesReport.FromDate = DateTime.Today;
            vmMarketingSalesReport.ToDate = DateTime.Today;
            vmMarketingSalesReport.ProductCategoryList = new SelectList(_service.ProductCategoryDropDownList(), "Value", "Text");
            vmMarketingSalesReport.ShopList = new SelectList(_service.CommonShopDropDownList(), "Value", "Text");
            vmMarketingSalesReport.SupplierList = new SelectList(_service.CommonSupplierDropDownList(), "Value", "Text");


            return View(vmMarketingSalesReport);
        }

       
        [HttpPost]
        public ActionResult SalesReportRDLCGet(VMMarketingSalesSlave vmMarketingSalesSlave)
        {
            var FromDate = vmMarketingSalesSlave.FromDate.ToString("yyyy-MM-dd");
            var ToDate = vmMarketingSalesSlave.ToDate.ToString("yyyy-MM-dd");

            NetworkCredential nwc = new NetworkCredential("Administrator", "Gocorona!9");
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = "";
            if (vmMarketingSalesSlave.IsSalesSummery == true)
            {
                reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/SalesReports&rs:Command=Render&rs:Format={0}&IsSalesSummery={1}&FromDate={2}&ToDate={3}&Common_ShopFK={4}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsSalesSummery, FromDate, ToDate, vmMarketingSalesSlave.Common_ShopFK);

            }
            else if (vmMarketingSalesSlave.IsCategoryWise == true)
            {
                reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/CategoryWiseSalesReports&rs:Command=Render&rs:Format={0}&IsCategoryWise={1}&FromDate={2}&ToDate={3}&Common_ProductCategoryFK={4}&Common_ShopFK={5}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsCategoryWise, FromDate, ToDate, vmMarketingSalesSlave.Common_ProductCategoryFK, vmMarketingSalesSlave.Common_ShopFK);

            }
            else if (vmMarketingSalesSlave.IsSupplierWise == true)
            {
                reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/SupplierWiseSalesReports&rs:Command=Render&rs:Format={0}&IsSupplierWise={1}&FromDate={2}&ToDate={3}&Common_SupplierFK={4}&Common_ShopFK={5}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsSupplierWise, FromDate, ToDate, vmMarketingSalesSlave.Common_SupplierFk, vmMarketingSalesSlave.Common_ShopFK);

            }

            //KGeCom
            //if (vmMarketingSalesSlave.IsSalesSummery == true)
            //{

            //    reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/KGeComSalesReports&rs:Command=Render&rs:Format={0}&IsSalesSummery={1}&FromDate={2}&ToDate={3}&Common_ShopFK={4}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsSalesSummery, FromDate, ToDate, vmMarketingSalesSlave.Common_ShopFK);

            //}
            //else if (vmMarketingSalesSlave.IsCategoryWise == true)
            //{
            //    reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/KGeComCategoryWiseSalesReports&rs:Command=Render&rs:Format={0}&IsCategoryWise={1}&FromDate={2}&ToDate={3}&Common_ProductCategoryFK={4}&Common_ShopFK={5}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsCategoryWise, FromDate, ToDate, vmMarketingSalesSlave.Common_ProductCategoryFK, vmMarketingSalesSlave.Common_ShopFK);

            //}
            //else if (vmMarketingSalesSlave.IsSupplierWise == true)
            //{
            //    reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/KGeComSupplierWiseSalesReports&rs:Command=Render&rs:Format={0}&IsSupplierWise={1}&FromDate={2}&ToDate={3}&Common_SupplierFK={4}&Common_ShopFK={5}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsSupplierWise, FromDate, ToDate, vmMarketingSalesSlave.Common_SupplierFk, vmMarketingSalesSlave.Common_ShopFK);

            //}
            //else
            //{
            //}

            if (vmMarketingSalesSlave.ReportType.Equals(ReportType.EXCEL))
            {
                return File(client.DownloadData(reportURL), "application/vnd.ms-excel", "ProdReference.xls");
            }
            if (vmMarketingSalesSlave.ReportType.Equals(ReportType.PDF))
            {
                return File(client.DownloadData(reportURL), "application/pdf");

            }
            if (vmMarketingSalesSlave.ReportType.Equals(ReportType.WORD))
            {
                return File(client.DownloadData(reportURL), "application/msword", "ProdReference.doc");
            }

            return View();

        }
        [HttpGet]
        public async Task<IActionResult> MarketingKGeComReportSalesReport()
        {
            VMMarketingSalesReport vmMarketingSalesReport = new VMMarketingSalesReport();
            vmMarketingSalesReport.FromDate = DateTime.Today;
            vmMarketingSalesReport.ToDate = DateTime.Today;
            vmMarketingSalesReport.ProductCategoryList = new SelectList(_service.ProductCategoryDropDownList(), "Value", "Text");
            vmMarketingSalesReport.ShopList = new SelectList(_service.CommonShopDropDownList(), "Value", "Text");
            vmMarketingSalesReport.SupplierList = new SelectList(_service.CommonSupplierDropDownList(), "Value", "Text");


            return View(vmMarketingSalesReport);
        }


        [HttpPost]
        public ActionResult SalesKGeComReportRDLCGet(VMMarketingSalesSlave vmMarketingSalesSlave)
        {
            var FromDate = vmMarketingSalesSlave.FromDate.ToString("yyyy-MM-dd");
            var ToDate = vmMarketingSalesSlave.ToDate.ToString("yyyy-MM-dd");

            NetworkCredential nwc = new NetworkCredential("Administrator", "Gocorona!9");
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = "";


            //KGeCom
            if (vmMarketingSalesSlave.IsSalesSummery == true)
            {

                reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/KGeComSalesReports&rs:Command=Render&rs:Format={0}&IsSalesSummery={1}&FromDate={2}&ToDate={3}&Common_ShopFK={4}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsSalesSummery, FromDate, ToDate, vmMarketingSalesSlave.Common_ShopFK);

            }
            else if (vmMarketingSalesSlave.IsCategoryWise == true)
            {
                reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/KGeComCategoryWiseSalesReports&rs:Command=Render&rs:Format={0}&IsCategoryWise={1}&FromDate={2}&ToDate={3}&Common_ProductCategoryFK={4}&Common_ShopFK={5}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsCategoryWise, FromDate, ToDate, vmMarketingSalesSlave.Common_ProductCategoryFK, vmMarketingSalesSlave.Common_ShopFK);

            }
            else if (vmMarketingSalesSlave.IsSupplierWise == true)
            {
                reportURL = string.Format("http://192.168.0.7/ReportServer_SQLEXPRESS/?%2fPos.RDL/KGeComSupplierWiseSalesReports&rs:Command=Render&rs:Format={0}&IsSupplierWise={1}&FromDate={2}&ToDate={3}&Common_SupplierFK={4}&Common_ShopFK={5}", vmMarketingSalesSlave.ReportType, vmMarketingSalesSlave.IsSupplierWise, FromDate, ToDate, vmMarketingSalesSlave.Common_SupplierFk, vmMarketingSalesSlave.Common_ShopFK);

            }
          

            if (vmMarketingSalesSlave.ReportType.Equals(ReportType.EXCEL))
            {
                return File(client.DownloadData(reportURL), "application/vnd.ms-excel", "ProdReference.xls");
            }
            if (vmMarketingSalesSlave.ReportType.Equals(ReportType.PDF))
            {
                return File(client.DownloadData(reportURL), "application/pdf");

            }
            if (vmMarketingSalesSlave.ReportType.Equals(ReportType.WORD))
            {
                return File(client.DownloadData(reportURL), "application/msword", "ProdReference.doc");
            }

            return View();

        }

        [HttpGet]
        public async Task<IActionResult> MarketingBazaarBakSalesReport()
        {
            VMMarketingSalesReport vmMarketingSalesReport = new VMMarketingSalesReport();
            vmMarketingSalesReport.FromDate = DateTime.Today;
            vmMarketingSalesReport.ToDate = DateTime.Today;

KG.Pos.App/Views/Marketing/CustomerDueReport.cshtml
@using KG.Core.Services

@{

    ViewData["Title"] = "Customer Due";
    Layout = "~/Views/Shared/_Layout.cshtml";


}
@model KG.Core.Services.Marketing.VMMarketingSalesSlave
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>

    <style type="text/css">

        input, select, textarea {
            max-width: 100%;
        }
    </style>
    <section class="content-header">
        <h1>
            Customer Due
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li class="active">Customer Due</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("CustomerDueReportView", "Marketing", FormMethod.Post, new { id = "customerDueReportViewFormId", @class = "formValidator", @target = "_blank", @enctype = "multipart/form-data" }))
                {
                    <div class="box">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="box-danger">

                            <!-- /.box-header -->
                            <div class="box-body">

                                @Html.HiddenFor(model => model.ActionId, new { id = "ActionId" })

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="message-text" class="col-form-label">Shop:</label>
                                            @Html.DropDownListFor(model => model.Common_ShopFK, Model.ShopList as SelectList, "==Select Shop==", new { id = "ddlCommon_ProductCategoryFk", @class = "searchingDropdown form-control" })
                                            @Html.ValidationMessageFor(model => model.Common_ShopFK, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="message-text" class="col-form-label">From Date:</label>
                                            <input name="FromDate" asp-for="FromDate" type="text" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="datePicker form-control" id="txtFromDate" placeholder="From Date" autocomplete="off">

                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="message-text" class="col-form-label">ToDate:</label>
                                            <input name="ToDate" asp-for="ToDate" type="text" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="datePicker form-control" id="txtToDate" placeholder="To Date" autocomplete="off">

                                        </div>
                                    </div>
                                </div>

                             

                                <div class="form-group">
                                    <div class="col-md-3">
                                        <button type="button" onclick="resetForm()" class="btn btn-secondary" data-dismiss="modal">Reset</button>
                                    </div>
                                    <div class="col-md-9">
                                        <button type="submit" id="btnSave" class="btn btn-primary btn-block"><i class='fa fa-shower'></i> Show Inventory</button>

                                    </div>

                                </div>
                            </div>
                                <div class="box-footer">
                                </div>

                            </div>
                    </div>
                }


            </div>

        </div>
    </section>


    @section scripts {

        <script type="text/javascript">


        $(document).ready(function () {

             //$('.formValidator').bootstrapValidator();





        });


        function resetForm() {
            $('#customerDueReportViewFormId')[0].reset();


        }
        </script>
    }

KG.Pos.App/Views/Marketing/CustomerInvoiceReport.cshtml
@using KG.Core.Services

@{

    ViewData["Title"] = "Customer Due";
    Layout = "~/Views/Shared/_Layout.cshtml";


}
@model KG.Core.Services.Marketing.VMMarketingSalesSlave
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>

    <style type="text/css">

        input, select, textarea {
            max-width: 100%;
        }
    </style>
    <section class="content-header">
        <h1>
            Customer Info
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li class="active">Customer Info</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("CustomerInvoiceReportView", "Marketing", FormMethod.Post, new { id = "customerDueReportViewFormId", @class = "formValidator", @target = "_blank", @enctype = "multipart/form-data" }))
                {
                    <div class="box">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="box-danger">

                            <!-- /.box-header -->
                            <div class="box-body">

                                @Html.HiddenFor(model => model.ActionId, new { id = "ActionId" })

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="message-text" class="col-form-label">Shop:</label>
                                            @Html.DropDownListFor(model => model.Common_ShopFK, Model.ShopList as SelectList, "==Select Shop==", new { id = "ddlCommon_ProductCategoryFk", @class = "searchingDropdown form-control", @required = "required" })
                                            @Html.ValidationMessageFor(model => model.Common_ShopFK, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="message-text" class="col-form-label">From Date:</label>
                                            <input name="FromDate" asp-for="FromDate" type="text" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="datePicker form-control" id="txtFromDate" placeholder="From Date" autocomplete="off">

                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="message-text" class="col-form-label">ToDate:</label>
                                            <input name="ToDate" asp-for="ToDate" type="text" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="datePicker form-control" id="txtToDate" placeholder="To Date" autocomplete="off">

                                        </div>
                                    </div>
                                </div>

                             

                                <div class="form-group">
                                    <div class="col-md-3">
                                        <button type="button" onclick="resetForm()" class="btn btn-secondary" data-dismiss="modal">Reset</button>
                                    </div>
                                    <div class="col-md-9">
                                        <button type="submit" id="btnSave" class="btn btn-primary btn-block"><i class='fa fa-shower'></i> Show Customer Info</button>

                                    </div>

                                </div>
                            </div>
                                <div class="box-footer">
                                </div>

                            </div>
                    </div>
                }


            </div>

        </div>
    </section>


    @section scripts {

        <script type="text/javascript">


        $(document).ready(function () {

             $('.formValidator').bootstrapValidator();





        });


        function resetForm() {
            $('#customerDueReportViewFormId')[0].reset();


        }
        </script>
    }

KG.Pos.App/Views/Marketing/MarketingBazaarBakSalesReport.cshtml
@{
    ViewData["Title"] = "Sales Report";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@model KG.Core.Services.Marketing.VMMarketingSalesReport
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>

    <section class="content-header">
        <h1>
            Sales Report 
           
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li class="active">Sales Report</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("SalesBazaarBakRDLCGet", "Marketing", FormMethod.Post, new { id = "marketingSalesReportformId", @class = "formValidator" ,target="_blank"}))
                {
                <div class="box">
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="box-danger">

                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group" style="padding:0px">
                                        <label>Brand:</label>
                                        @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @autocomplete = "on", @class = "form-control", @name = "Brand", @id = "txtBrand" } })

                                        @Html.HiddenFor(model => model.Common_BrandFk, new { id = "ddlCommon_BrandFk" })
                                    </div>

                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Category:</label>
                                        @Html.DropDownListFor(model => model.Common_ProductCategoryFK, Model.ProductCategoryList as SelectList, "---Select Category---", new { id = "ddlCommon_ProductCategoryFk", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.Common_ProductCategoryFK, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Subcategory:</label>
                                        @Html.DropDownListFor(model => model.Common_ProductSubCategoryFK, Model.ProductSubCategoryList as SelectList, "---Select Subcategory---", new { id = "ddlCommonProductSubCategoryFk", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.Common_ProductSubCategoryFK, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Item:</label>
                                        @Html.DropDownListFor(model => model.Common_ProductFK, Model.ProductList as SelectList, "---Select Item---", new { id = "ddlCommonProductFk", @class = "searchingDropdown form-control" })
                                        @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="col-sm-2  control-label">Shop</label>
                                        @Html.DropDownListFor(model => model.Common_ShopFK, Model.ShopList as SelectList, "== Select Shop ==", new { id = "ddlCommon_ShopFK", @class = "searchingDropdown form-control", style = "width:100%" })

                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="col-sm-2  control-label">Supplier</label>
                                        @Html.DropDownListFor(model => model.Common_SupplierFk, Model.SupplierList as SelectList, "== Select Supplier ==", new { id = "ddlCommon_SupplierFk", @class = "searchingDropdown form-control", style = "width:100%" })

                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">From Date:</label>
                                        <input name="FromDate" asp-for="FromDate" type="text" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="datePicker form-control" id="txtFromDate" placeholder="From Date" autocomplete="off">

                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">ToDate:</label>
                                        <input name="ToDate" asp-for="ToDate" type="text" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="datePicker form-control" id="txtToDate" placeholder="To Date" autocomplete="off">

                                    </div>
                                </div>
                            </div>
                            <input type="checkbox" asp-for="IsSalesSummery" name="IsSalesSummery" />  Sales Summery

                            <input type="checkbox" asp-for="IsCategoryWise" name="IsCategoryWise" />  Category Wise

                            <input type="checkbox" asp-for="IsSupplierWise" name="IsSupplierWise" />  Supplier Wise


                            <div class="form-group">
                                <input type="submit" name="EXPORT" value="EXPORT" class="btn btn-success pull-right" formtarget="_blank" />
                                <select asp-for="ReportType" class="pull-right" style="color:#ffffff; background-color:#dd4b39;height:34px;font-size:15px" name="ReportType" id="ddlReportType">
                                    <option value="PDF">PDF</option>
                                    <option value="EXCEL">EXCEL</option>
                                    <option value="WORD">WORD</option>
                                </select>

                            </div>
                        </div>
                        <div class="box-footer">
                        </div>

                    </div>
                </div>
                }


            </div>

        </div>
    </section>



    @section scripts {

        <script type="text/javascript">


            $(document).ready(function () {

                 $("#txtBrand").autocomplete({
                source: function (request, response) {
                    //console.log(request);
                    //console.log(response);

                    $.ajax({
                        url:"@Url.Action("AutoCompleteBrandGet", "Configuration")",// '/AccountHeads/AutoComplete/',
                        //data: "{ 'prefix': '" + request.term + "'}",
                        data: { id : request.term },
                        dataType: "json",
                        type: "get",
                        cache: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            //alert(response.responseText);
                        },
                        failure: function (response) {
                            //alert(response.responseText);
                        }
                    });
                },

                select: function (e, i) {
                    $("#ddlCommon_BrandFk").val(i.item.val);


                    },
                    autoFocus: true,
                minLength: 1,
                cache: true

            }).focus(function () {
                $(this).autocomplete("search");
            });

           // $('.formValidator').bootstrapValidator();
           $("#ddlCommon_ProductCategoryFk").change(function () {

                var productCategoryFk = $("#ddlCommon_ProductCategoryFk").val();
                     $.ajax({
                type: "GET",
                url: "@Url.Action("GetCommonProductSubCategory", "WareHouse")",
                datatype: "Json",
                         data: { id: productCategoryFk},
                    success: function (data) {
                    var items = "";
                        if (data) {
                            $("#ddlCommonProductSubCategoryFk").empty();
                            $("#ddlCommonProductSubCategoryFk").append("<option value=''>==Select Subcategory==</option>");
                            $(data).each(function (index, item) {
                                $("#ddlCommonProductSubCategoryFk").append("<option value='" + item.value + "'>" + item.text + "</option>");
                            });

                        }
                    }
                });
            })


            $("#ddlCommonProductSubCategoryFk").change(function () {

                var productSubCategoryFk = $("#ddlCommonProductSubCategoryFk").val();
                     $.ajax({
                type: "GET",
                url: "@Url.Action("GetCommonProduct", "WareHouse")",
                datatype: "Json",
                         data: {  id : productSubCategoryFk},
                    success: function (data) {
                    var items = "";
                        if (data) {
                            $("#ddlCommonProductFk").empty();
                            $("#ddlCommonProductFk").append("<option value=''>==Select Item==</option>");
                            $(data).each(function (index, item) {
                                $("#ddlCommonProductFk").append("<option value='" + item.value + "'>" + item.text + "</option>");
                            });

                        }
                    }
                });
            })





        });

            function resetForm() {
                $('#wareHouseRawItemInventoryformId')[0].reset();


            }
        </script>
    }